/**
 * Response Messages
 */

export const MESSAGE_ERROR = 'ERROR'
export const MESSAGE_FAILED = 'FAILED'

export const MESSAGE_SUCCESS = 'SUCCESS'
export const MESSAGE_CREATED = 'CREATED'
export const MESSAGE_UPDATED = 'UPDATED'
export const MESSAGE_DELETED = 'DELETED'
export const MESSAGE_FOUND = 'FOUND'
export const MESSAGE_NOT_FOUND = 'NOT_FOUND'
export const MESSAGE_BAD_REQUEST = 'BAD_REQUEST'
export const MESSAGE_UNAUTHORIZED = 'UNAUTHORIZED'
export const MESSAGE_FORBIDDEN = 'FORBIDDEN'
export const MESSAGE_INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
export const MESSAGE_NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
export const MESSAGE_NOT_ACCEPTABLE = 'NOT_ACCEPTABLE'
export const MESSAGE_CONFLICT = 'CONFLICT'
export const MESSAGE_NO_CONTENT = 'NO_CONTENT'
export const MESSAGE_RESET_CONTENT = 'RESET_CONTENT'
export const MESSAGE_PARTIAL_CONTENT = 'PARTIAL_CONTENT'
export const MESSAGE_MOVED_PERMANENTLY = 'MOVED_PERMANENTLY'
export const MESSAGE_FOUND_MOVED = 'FOUND_MOVED'
export const MESSAGE_SEE_OTHER = 'SEE_OTHER'
export const MESSAGE_NOT_MODIFIED = 'NOT_MODIFIED'
export const MESSAGE_USE_PROXY = 'USE_PROXY'
export const MESSAGE_TEMPORARY_REDIRECT = 'TEMPORARY_REDIRECT'
export const MESSAGE_PERMANENT_REDIRECT = 'PERMANENT_REDIRECT'
export const MESSAGE_BAD_GATEWAY = 'BAD_GATEWAY'
export const MESSAGE_SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
export const MESSAGE_GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT'
export const MESSAGE_HTTP_VERSION_NOT_SUPPORTED = 'HTTP_VERSION_NOT_SUPPORTED'
export const MESSAGE_VARIANT_ALSO_NEGOTIATES = 'VARIANT_ALSO_NEGOTIATES'
export const MESSAGE_INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE'
export const MESSAGE_LOOP_DETECTED = 'LOOP_DETECTED'
export const MESSAGE_BANDWIDTH_LIMIT_EXCEEDED = 'BANDWIDTH_LIMIT_EXCEEDED'
export const MESSAGE_NOT_EXTENDED = 'NOT_EXTENDED'
export const MESSAGE_NETWORK_AUTHENTICATION_REQUIRED =
  'NETWORK_AUTHENTICATION_REQUIRED'
export const MESSAGE_NETWORK_CONNECT_TIMEOUT_ERROR =
  'NETWORK_CONNECT_TIMEOUT_ERROR'
export const MESSAGE_NETWORK_READ_TIMEOUT_ERROR = 'NETWORK_READ_TIMEOUT_ERROR'
export const MESSAGE_NETWORK_ERROR = 'NETWORK_ERROR'
export const MESSAGE_NETWORK_ERROR_UNKNOWN = 'NETWORK_ERROR_UNKNOWN'
export const MESSAGE_NETWORK_ERROR_OFFLINE = 'NETWORK_ERROR_OFFLINE'
export const MESSAGE_NETWORK_ERROR_HOST = 'NETWORK_ERROR_HOST'
export const MESSAGE_NETWORK_ERROR_UNAUTHORIZED = 'NETWORK_ERROR_UNAUTHORIZED'
export const MESSAGE_NETWORK_ERROR_FORBIDDEN = 'NETWORK_ERROR_FORBIDDEN'
export const MESSAGE_NETWORK_ERROR_NOT_FOUND = 'NETWORK_ERROR_NOT_FOUND'
export const MESSAGE_NETWORK_ERROR_INTERNAL_SERVER =
  'NETWORK_ERROR_INTERNAL_SERVER'
export const MESSAGE_NETWORK_ERROR_BAD_GATEWAY = 'NETWORK_ERROR_BAD_GATEWAY'
export const MESSAGE_NETWORK_ERROR_SERVICE_UNAVAILABLE =
  'NETWORK_ERROR_SERVICE_UNAVAILABLE'
export const MESSAGE_NETWORK_ERROR_GATEWAY_TIMEOUT =
  'NETWORK_ERROR_GATEWAY_TIMEOUT'
export const MESSAGE_NETWORK_ERROR_UNKNOWN_HOST = 'NETWORK_ERROR_UNKNOWN_HOST'
export const MESSAGE_NETWORK_ERROR_NOT_IMPLEMENTED =
  'NETWORK_ERROR_NOT_IMPLEMENTED'
export const MESSAGE_NETWORK_ERROR_BAD_REQUEST = 'NETWORK_ERROR_BAD_REQUEST'
export const MESSAGE_NETWORK_ERROR_UNPROCESSABLE_ENTITY =
  'NETWORK_ERROR_UNPROCESSABLE_ENTITY'
export const MESSAGE_NETWORK_ERROR_LOCKED = 'NETWORK_ERROR_LOCKED'
export const MESSAGE_NETWORK_ERROR_FAILED_DEPENDENCY =
  'NETWORK_ERROR_FAILED_DEPENDENCY'
export const MESSAGE_NETWORK_ERROR_UPGRADE_REQUIRED =
  'NETWORK_ERROR_UPGRADE_REQUIRED'
export const MESSAGE_NETWORK_ERROR_PRECONDITION_FAILED =
  'NETWORK_ERROR_PRECONDITION_FAILED'
export const MESSAGE_NETWORK_ERROR_TOO_MANY_REQUESTS =
  'NETWORK_ERROR_TOO_MANY_REQUESTS'

/**
 * Authorization Commands
 */
export const MESSAGE_AUTHORIZE = 'AUTHORIZE'

/**
 * Configuration Commands
 */
export const MESSAGE_CREATE_CONFIGURATION = 'CREATE_CONFIGURATION'
export const MESSAGE_READ_CONFIGURATION = 'READ_CONFIGURATION'
export const MESSAGE_UPDATE_CONFIGURATION = 'UPDATE_CONFIGURATION'
export const MESSAGE_DELETE_CONFIGURATION = 'DELETE_CONFIGURATION'
export const MESSAGE_ACTIVATE_CONFIGURATION = 'ACTIVATE_CONFIGURATION'
export const MESSAGE_DEACTIVATE_CONFIGURATION = 'DEACTIVATE_CONFIGURATION'

/**
 * Account Commands
 */
export const MESSAGE_CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const MESSAGE_READ_ACCOUNT = 'READ_ACCOUNT'
export const MESSAGE_UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const MESSAGE_DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const MESSAGE_ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT'
export const MESSAGE_DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT'

/**
 * Order Commands
 */
export const MESSAGE_CREATE_ORDER = 'CREATE_ORDER'
export const MESSAGE_READ_ORDER = 'READ_ORDER'
export const MESSAGE_UPDATE_ORDER = 'UPDATE_ORDER'
export const MESSAGE_DELETE_ORDER = 'DELETE_ORDER'
